namespace PeriodicTable
{
    using System.Collections.ObjectModel;

    public class SubTableDataSource
    {
        public static Collection<Element> Create()
        {
            return new Collection<Element>
                {
                    new Element
                        {
                            Name = "Lanthanum",
                            AtomicNumber = 57,
                            ChemicalSymbol = "La",
                            RelativeAtomicMass = 138.90547,
                            MassUncertainty = 7,
                            NaturalOccurrence = NaturalOccurrence.Primordial,
                            ChemicalProperty = ChemicalProperty.Lanthanide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Lanthanum",
                            CountryOfDiscovery = CountryOfDiscovery.Sweden,
                        },
                    new Element
                        {
                            Name = "Cerium",
                            AtomicNumber = 58,
                            ChemicalSymbol = "Ce",
                            RelativeAtomicMass = 140.116,
                            MassUncertainty = 1,
                            NaturalOccurrence = NaturalOccurrence.Primordial,
                            ChemicalProperty = ChemicalProperty.Lanthanide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Cerium",
                            CountryOfDiscovery = CountryOfDiscovery.Austria,
                        },
                    new Element
                        {
                            Name = "Praseodymium",
                            AtomicNumber = 59,
                            ChemicalSymbol = "Pr",
                            RelativeAtomicMass = 140.90765,
                            MassUncertainty = 2,
                            NaturalOccurrence = NaturalOccurrence.Primordial,
                            ChemicalProperty = ChemicalProperty.Lanthanide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Praseodymium",
                            CountryOfDiscovery = CountryOfDiscovery.Austria,
                        },
                    new Element
                        {
                            Name = "Neodymium",
                            AtomicNumber = 60,
                            ChemicalSymbol = "Nd",
                            RelativeAtomicMass = 144.242,
                            MassUncertainty = 3,
                            NaturalOccurrence = NaturalOccurrence.Primordial,
                            ChemicalProperty = ChemicalProperty.Lanthanide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Neodymium",
                            CountryOfDiscovery = CountryOfDiscovery.Austria,
                        },
                    new Element
                        {
                            Name = "Promethium",
                            AtomicNumber = 61,
                            ChemicalSymbol = "Pm",
                            RelativeAtomicMass = 145,
                            MassUncertainty = 0,
                            NaturalOccurrence = NaturalOccurrence.FromDecay,
                            ChemicalProperty = ChemicalProperty.Lanthanide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Promethium",
                            CountryOfDiscovery = CountryOfDiscovery.Usa,
                        },
                    new Element
                        {
                            Name = "Samarium",
                            AtomicNumber = 62,
                            ChemicalSymbol = "Sm",
                            RelativeAtomicMass = 150.36,
                            MassUncertainty = 2,
                            NaturalOccurrence = NaturalOccurrence.Primordial,
                            ChemicalProperty = ChemicalProperty.Lanthanide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Samarium",
                            CountryOfDiscovery = CountryOfDiscovery.France,
                        },
                    new Element
                        {
                            Name = "Europium",
                            AtomicNumber = 63,
                            ChemicalSymbol = "Eu",
                            RelativeAtomicMass = 151.964,
                            MassUncertainty = 1,
                            NaturalOccurrence = NaturalOccurrence.Primordial,
                            ChemicalProperty = ChemicalProperty.Lanthanide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Europium",
                            CountryOfDiscovery = CountryOfDiscovery.France,
                        },
                    new Element
                        {
                            Name = "Gadolinium",
                            AtomicNumber = 64,
                            ChemicalSymbol = "Gd",
                            RelativeAtomicMass = 157.25,
                            MassUncertainty = 3,
                            NaturalOccurrence = NaturalOccurrence.Primordial,
                            ChemicalProperty = ChemicalProperty.Lanthanide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Gadolinium",
                            CountryOfDiscovery = CountryOfDiscovery.Switzerland,
                        },
                    new Element
                        {
                            Name = "Terbium",
                            AtomicNumber = 65,
                            ChemicalSymbol = "Tb",
                            RelativeAtomicMass = 158.92535,
                            MassUncertainty = 2,
                            NaturalOccurrence = NaturalOccurrence.Primordial,
                            ChemicalProperty = ChemicalProperty.Lanthanide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Terbium",
                            CountryOfDiscovery = CountryOfDiscovery.Sweden,
                        },
                    new Element
                        {
                            Name = "Dysprosium",
                            AtomicNumber = 66,
                            ChemicalSymbol = "Dy",
                            RelativeAtomicMass = "162.500",
                            MassUncertainty = 1,
                            NaturalOccurrence = NaturalOccurrence.Primordial,
                            ChemicalProperty = ChemicalProperty.Lanthanide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Dysprosium",
                            CountryOfDiscovery = CountryOfDiscovery.France,
                        },
                    new Element
                        {
                            Name = "Holmium",
                            AtomicNumber = 67,
                            ChemicalSymbol = "Ho",
                            RelativeAtomicMass = 164.93032,
                            MassUncertainty = 2,
                            NaturalOccurrence = NaturalOccurrence.Primordial,
                            ChemicalProperty = ChemicalProperty.Lanthanide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Holmium",
                            CountryOfDiscovery = CountryOfDiscovery.Sweden,
                        },
                    new Element
                        {
                            Name = "Erbium",
                            AtomicNumber = 68,
                            ChemicalSymbol = "Er",
                            RelativeAtomicMass = 167.259,
                            MassUncertainty = 3,
                            NaturalOccurrence = NaturalOccurrence.Primordial,
                            ChemicalProperty = ChemicalProperty.Lanthanide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Erbium",
                            CountryOfDiscovery = CountryOfDiscovery.Sweden,
                        },
                    new Element
                        {
                            Name = "Thulium",
                            AtomicNumber = 69,
                            ChemicalSymbol = "Tm",
                            RelativeAtomicMass = 168.93421,
                            MassUncertainty = 2,
                            NaturalOccurrence = NaturalOccurrence.Primordial,
                            ChemicalProperty = ChemicalProperty.Lanthanide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Thulium",
                            CountryOfDiscovery = CountryOfDiscovery.Sweden,
                        },
                    new Element
                        {
                            Name = "Ytterbium",
                            AtomicNumber = 70,
                            ChemicalSymbol = "Yb",
                            RelativeAtomicMass = 173.054,
                            MassUncertainty = 5,
                            NaturalOccurrence = NaturalOccurrence.Primordial,
                            ChemicalProperty = ChemicalProperty.Lanthanide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Ytterbium",
                            CountryOfDiscovery = CountryOfDiscovery.Switzerland,
                        },
                    new Element
                        {
                            Name = "Lutetium",
                            AtomicNumber = 71,
                            ChemicalSymbol = "Lu",
                            RelativeAtomicMass = 174.9668,
                            MassUncertainty = 1,
                            NaturalOccurrence = NaturalOccurrence.Primordial,
                            ChemicalProperty = ChemicalProperty.Lanthanide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Lutetium",
                            CountryOfDiscovery = CountryOfDiscovery.France,
                        },
                    new Element
                        {
                            Name = "Actinium",
                            AtomicNumber = 89,
                            ChemicalSymbol = "Ac",
                            RelativeAtomicMass = 227,
                            MassUncertainty = 0,
                            NaturalOccurrence = NaturalOccurrence.FromDecay,
                            ChemicalProperty = ChemicalProperty.Actinide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Actinium",
                            CountryOfDiscovery = CountryOfDiscovery.France,
                        },
                    new Element
                        {
                            Name = "Thorium",
                            AtomicNumber = 90,
                            ChemicalSymbol = "Th",
                            RelativeAtomicMass = 232.03806,
                            MassUncertainty = 2,
                            NaturalOccurrence = NaturalOccurrence.Primordial,
                            ChemicalProperty = ChemicalProperty.Actinide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Thorium",
                            CountryOfDiscovery = CountryOfDiscovery.Sweden,
                        },
                    new Element
                        {
                            Name = "Protactinium",
                            AtomicNumber = 91,
                            ChemicalSymbol = "Pa",
                            RelativeAtomicMass = 231.03588,
                            MassUncertainty = 2,
                            NaturalOccurrence = NaturalOccurrence.FromDecay,
                            ChemicalProperty = ChemicalProperty.Actinide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Protactinium",
                            CountryOfDiscovery = CountryOfDiscovery.UkGermany,
                        },
                    new Element
                        {
                            Name = "Uranium",
                            AtomicNumber = 92,
                            ChemicalSymbol = "U",
                            RelativeAtomicMass = 238.02891,
                            MassUncertainty = 3,
                            NaturalOccurrence = NaturalOccurrence.Primordial,
                            ChemicalProperty = ChemicalProperty.Actinide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Uranium",
                            CountryOfDiscovery = CountryOfDiscovery.Germany,
                        },
                    new Element
                        {
                            Name = "Neptunium",
                            AtomicNumber = 93,
                            ChemicalSymbol = "Np",
                            RelativeAtomicMass = 237,
                            MassUncertainty = 0,
                            NaturalOccurrence = NaturalOccurrence.FromDecay,
                            ChemicalProperty = ChemicalProperty.Actinide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Neptunium",
                            CountryOfDiscovery = CountryOfDiscovery.Usa,
                        },
                    new Element
                        {
                            Name = "Plutonium",
                            AtomicNumber = 94,
                            ChemicalSymbol = "Pu",
                            RelativeAtomicMass = 244,
                            MassUncertainty = 0,
                            NaturalOccurrence = NaturalOccurrence.Primordial,
                            ChemicalProperty = ChemicalProperty.Actinide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Plutonium",
                            CountryOfDiscovery = CountryOfDiscovery.Usa,
                        },
                    new Element
                        {
                            Name = "Americium",
                            AtomicNumber = 95,
                            ChemicalSymbol = "Am",
                            RelativeAtomicMass = 243,
                            MassUncertainty = 0,
                            NaturalOccurrence = NaturalOccurrence.FromDecay,
                            ChemicalProperty = ChemicalProperty.Actinide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Americium",
                            CountryOfDiscovery = CountryOfDiscovery.Usa,
                        },
                    new Element
                        {
                            Name = "Curium",
                            AtomicNumber = 96,
                            ChemicalSymbol = "Cm",
                            RelativeAtomicMass = 247,
                            MassUncertainty = 0,
                            NaturalOccurrence = NaturalOccurrence.FromDecay,
                            ChemicalProperty = ChemicalProperty.Actinide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Curium",
                            CountryOfDiscovery = CountryOfDiscovery.Usa,
                        },
                    new Element
                        {
                            Name = "Berkelium",
                            AtomicNumber = 97,
                            ChemicalSymbol = "Bk",
                            RelativeAtomicMass = 247,
                            MassUncertainty = 0,
                            NaturalOccurrence = NaturalOccurrence.FromDecay,
                            ChemicalProperty = ChemicalProperty.Actinide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Berkelium",
                            CountryOfDiscovery = CountryOfDiscovery.Usa,
                        },
                    new Element
                        {
                            Name = "Californium",
                            AtomicNumber = 98,
                            ChemicalSymbol = "Cf",
                            RelativeAtomicMass = 253,
                            MassUncertainty = 0,
                            NaturalOccurrence = NaturalOccurrence.FromDecay,
                            ChemicalProperty = ChemicalProperty.Actinide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Californium",
                            CountryOfDiscovery = CountryOfDiscovery.Usa,
                        },
                    new Element
                        {
                            Name = "Einsteinium",
                            AtomicNumber = 99,
                            ChemicalSymbol = "Es",
                            RelativeAtomicMass = 252,
                            MassUncertainty = 0,
                            NaturalOccurrence = NaturalOccurrence.Synthetic,
                            ChemicalProperty = ChemicalProperty.Actinide,
                            State = State.Solid,
                            Url = "http://en.wikipedia.org/wiki/Ensteinium",
                            CountryOfDiscovery = CountryOfDiscovery.Usa,
                        },
                    new Element
                        {
                            Name = "Fermium",
                            AtomicNumber = 100,
                            ChemicalSymbol = "Fm",
                            RelativeAtomicMass = 257,
                            MassUncertainty = 0,
                            NaturalOccurrence = NaturalOccurrence.Synthetic,
                            ChemicalProperty = ChemicalProperty.Actinide,
                            State = State.Unknown,
                            Url = "http://en.wikipedia.org/wiki/Fermium",
                            CountryOfDiscovery = CountryOfDiscovery.Usa,
                        },
                    new Element
                        {
                            Name = "Mendelevium",
                            AtomicNumber = 101,
                            ChemicalSymbol = "Md",
                            RelativeAtomicMass = 258,
                            MassUncertainty = 0,
                            NaturalOccurrence = NaturalOccurrence.Synthetic,
                            ChemicalProperty = ChemicalProperty.Actinide,
                            State = State.Unknown,
                            Url = "http://en.wikipedia.org/wiki/Mendelevium",
                            CountryOfDiscovery = CountryOfDiscovery.Usa,
                        },
                    new Element
                        {
                            Name = "Nobelium",
                            AtomicNumber = 102,
                            ChemicalSymbol = "No",
                            RelativeAtomicMass = 259,
                            MassUncertainty = 0,
                            NaturalOccurrence = NaturalOccurrence.Synthetic,
                            ChemicalProperty = ChemicalProperty.Actinide,
                            State = State.Unknown,
                            Url = "http://en.wikipedia.org/wiki/Nobelium",
                            CountryOfDiscovery = CountryOfDiscovery.Russia,
                        },
                    new Element
                        {
                            Name = "Lawrencium",
                            AtomicNumber = 103,
                            ChemicalSymbol = "Lr",
                            RelativeAtomicMass = 262,
                            MassUncertainty = 0,
                            NaturalOccurrence = NaturalOccurrence.Synthetic,
                            ChemicalProperty = ChemicalProperty.Actinide,
                            State = State.Unknown,
                            Url = "http://en.wikipedia.org/wiki/Lawrencium",
                            CountryOfDiscovery = CountryOfDiscovery.Usa,
                        },
                };
        }
    }
}
